name: TelewireAnalytics
channels:
  - defaults
  - conda-forge
  - ericmjl
dependencies:
  - python=3.9.13
  - pandas=1.3.3
  - matplotlib=3.4.3
  - jupyterlab=3.2.0
  - seaborn=0.11.2
  - joblib==1.2.0
  - numpy==1.24.2
  - plotly==5.14.0
  - xgboost==1.7.4
  - altair==4.2.2
  - dill==0.3.6
  - kiwisolver
  - libstdcxx-ng=9.3.0
  - pip
  - streamlit
  - scikit-learn==1.0.2
  - sklearn==0.0
  - setuptools-git==1.2
  - cmdstanpy==0.9.5
